"""add auth users

Revision ID: 19a818149298
Revises: 321986e111da
Create Date: 2026-08-14 21:33:02.446274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19a818149298'
down_revision: Union[str, Sequence[str], None] = '321986e111da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "auth_users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_index(
        op.f("ix_auth_users_email"),
        "auth_users",
        ["email"],
        unique=True,
    )

    # Create AuthUser records for existing development users.
    op.execute(
        sa.text(
            """
            INSERT INTO auth_users (
                id,
                email,
                password_hash,
                is_active
            )
            VALUES
                (
                    'd92b1640-1edb-42ef-aeb8-666889d1bbad',
                    'admin@acme.local',
                    'CHANGE_ME',
                    true
                ),
                (
                    'c3b7a849-b043-48ac-9668-eb43a3144205',
                    'employee@acme.local',
                    'CHANGE_ME',
                    true
                ),
                (
                    'da1459b3-e997-4ee6-a640-14c214d2a22a',
                    'technician@acme.local',
                    'CHANGE_ME',
                    true
                )
            """
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auth_users_email'), table_name='auth_users')
    op.drop_table('auth_users')
    # ### end Alembic commands ###
