"""link users to auth users

Revision ID: 4d3844f51ba0
Revises: 19a818149298
Create Date: 2026-08-14 22:17:37.768520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d3844f51ba0'
down_revision: Union[str, Sequence[str], None] = '19a818149298'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_auth_user_id'), table_name='users')
    op.create_index(op.f('ix_users_auth_user_id'), 'users', ['auth_user_id'], unique=True)
    op.create_foreign_key("fk_users_auth_user_id", 'users', 'auth_users', ['auth_user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_users_auth_user_id", 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_auth_user_id'), table_name='users')
    op.create_index(op.f('ix_users_auth_user_id'), 'users', ['auth_user_id'], unique=False)
    # ### end Alembic commands ###
