TICKET_STATUS_OPEN = "OPEN"
TICKET_STATUS_IN_PROGRESS = "IN_PROGRESS"
TICKET_STATUS_WAITING_FOR_USER = "WAITING_FOR_USER"
TICKET_STATUS_WAITING_FOR_VENDOR = "WAITING_FOR_VENDOR"
TICKET_STATUS_RESOLVED = "RESOLVED"
TICKET_STATUS_CLOSED = "CLOSED"


TICKET_STATUSES = frozenset(
    {
        TICKET_STATUS_OPEN,
        TICKET_STATUS_IN_PROGRESS,
        TICKET_STATUS_WAITING_FOR_USER,
        TICKET_STATUS_WAITING_FOR_VENDOR,
        TICKET_STATUS_RESOLVED,
        TICKET_STATUS_CLOSED,
    }
)


TICKET_STATUS_TRANSITIONS = {
    TICKET_STATUS_OPEN: frozenset(
        {
            TICKET_STATUS_IN_PROGRESS,
        }
    ),
    TICKET_STATUS_IN_PROGRESS: frozenset(
        {
            TICKET_STATUS_WAITING_FOR_USER,
            TICKET_STATUS_WAITING_FOR_VENDOR,
            TICKET_STATUS_RESOLVED,
        }
    ),
    TICKET_STATUS_WAITING_FOR_USER: frozenset(
        {
            TICKET_STATUS_IN_PROGRESS,
        }
    ),
    TICKET_STATUS_WAITING_FOR_VENDOR: frozenset(
        {
            TICKET_STATUS_IN_PROGRESS,
        }
    ),
    TICKET_STATUS_RESOLVED: frozenset(
        {
            TICKET_STATUS_IN_PROGRESS,
            TICKET_STATUS_CLOSED,
        }
    ),
    TICKET_STATUS_CLOSED: frozenset(),
}